version: '3.7'

services:
  toba:
    image: ${REGISTRY_HOSTNAME?err}toba:${APP_ENVIRONMENT:?err}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROYECTO_DIR=${PROYECTO_DIR:?err}
        - APP_ENVIRONMENT=${APP_ENVIRONMENT:?err}
    ports:
      - 8000:80
    volumes:
      # La configuración de Apache
      - type: volume
        source: apache-conf
        target: /etc/apache2/sites-enabled
      # Instalación de Toba
      - type: volume
        source: toba-data
        target: ${TOBA_DIR:?err}
      # Proyectos
      - type: volume
        source: proyecto-data
        target: ${PROYECTO_DIR:?err}/proyectos
    depends_on:
      - db
    environment:
      TOBA_INSTANCIA: toba_tuto
      TOBA_INSTALACION_DIR: ${TOBA_DIR:?err}
  db:
    image: postgres:9.6.17
    environment:
      POSTGRES_USER: ${DB_USER:?err}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data:
  toba-data:
  apache-conf:
  proyecto-data:

