version: '3.7'

services:
  toba:
    image: toba:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_DIR=${BASE_DIR:?err}
        - ES_PRODUCCION=${ES_PRODUCCION:?err}
        - UID=${UID:?err}
    ports:
      - 8000:80
    volumes:
      # La configuración de Apache
      - type: volume
        source: apache-conf
        target: /etc/apache2/sites-enabled
      # Instalación de Toba
      - type: volume
        source: toba-data
        target: ${BASE_DIR:?err}/instalacion
      # Proyectos
      - type: bind
        source: ./proyectos
        target: ${BASE_DIR:?err}/proyectos
    depends_on:
      - db
    environment:
      TOBA_INSTANCIA: ${TOBA_INSTANCIA_NOMBRE:?err}
      TOBA_INSTALACION_DIR: ${BASE_DIR:?err}/instalacion
      DB_USER: ${DB_USER:?err}
      DB_PASSWORD: ${DB_PASSWORD:?err}
      TOBA_USUARIO: ${TOBA_USUARIO:?err}
      TOBA_PASSWORD: ${TOBA_PASSWORD:?err}
      ID_DESARROLLADOR: ${ID_DESARROLLADOR:?err}
      ES_PRODUCCION: ${ES_PRODUCCION:?err}
      TOBA_SCHEMA_NOMBRE: ${TOBA_SCHEMA_NOMBRE:?err}
  db:
    image: postgres:9.6.17
    environment:
      POSTGRES_USER: ${DB_USER:?err}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data:
  toba-data:
  apache-conf:

